import Head from 'next/head'
import DisplayRepos from '../componenets/displayRepos'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import Image from 'next/image'

export default function Home({ repos }) {
  // const [searchTerm, setSearchTerm] = useState('')
  const [searchResults, setSearchResults] = useState(repos)

  const handleChange = (e) => {
    // setSearchTerm(e.target.value)
    filterRepos(e.target.value)
  }

  // filter repos by search term in name or description
  const filterRepos = (searchTerm) => {
    const filteredRepos = repos.filter((repo) => {
      return (
        repo?.name?.toLowerCase().includes(searchTerm.toLowerCase()) ||
        repo?.description?.toLowerCase().includes(searchTerm.toLowerCase())
      )
    })
    setSearchResults(filteredRepos)
  }





  return (
    <div className={styles.container}>
      <Head>
        <title>Faraday Github Repos</title>
        <meta name="description" content="Generated by Rob Boskind" />
        <link rel="icon" href="/faraday.svg" />
      </Head>

      <main className={styles.main}>
        <Image src="/faraday.svg"
          alt="faraday logo"
          className={styles.logo}
          width={100}
          height={100}
        />
        <h1 className={styles.title}>
          Welcome to
          <a href="https://faraday.ai/"> Faraday</a>
        </h1>
        <h2 className={styles.description}>
          This is a sample page for finding Github repos from Faraday.ai
        </h2>
        <input className={styles.search} type="text" placeholder="Search for a repo by name or description" onChange={handleChange} />

        <DisplayRepos reposToDisplay={searchResults} />
      </main>

      <footer className={styles.footer}>
        <p className={styles.description}>
          For more information, visit{' '}
          <a href="https://github.com/mysticfalconvt/faraday-github-exercise">My Repo</a>
        </p>
        <p>

          <a
            href="https://portfolio.boskind.tech/"
            target="_blank"
            rel="noopener noreferrer"
          >
            Created by Rob Boskind
          </a>
        </p>
      </footer>
    </div>
  )
}

// get data from the GitHub Api
export async function getStaticProps(context) {
  // Call an external API endpoint to get repositories.
  const username = 'faradayio'
  const url = `https://api.github.com/users/${username}/repos`;

  //get the repos from the github api
  const reposWithAllInfo = await fetch(url)
    .then(response => response.json())
    .catch(error => console.log(error));
  // console.log(reposWithAllInfo)
  //get just the name, description, and html_url of each repo to reduce the size of the data
  const repos = reposWithAllInfo.map(repo => {
    return {
      name: repo.name,
      id: repo.id,
      description: repo.description,
      language: repo.language,
      html_url: repo.html_url
    }
  });


  return {
    props: { repos }, // will be passed to the page component as props
  }
}